spring.application.name=backend

# 1. TiDB Cloud Database Connection
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY&ssl=true&requireSSL=true
spring.datasource.username=3cQPjnC8kUJKQgQ.root
spring.datasource.password=eTsAMU78d4sMbusz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Hibernate Settings for MySQL/TiDB
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.batch_size=0

# 3. Server Port
server.port=8080