spring.application.name=backend
# 1. Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/kentwardrobe_db
spring.datasource.username=root
# enter your DB password
spring.datasource.password=

# 2. Hibernate Settings (Auto-create tables)
# "update" means: If you change a Java class, it updates the MySQL table automatically.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Server Port (Frontend is 3000, Backend will be 8080)
server.port=8080